version: '0.3'

services:
    main_service:
        image: main_service
        container_name: main_service
        ports:
            - 8001:8001
        networks:
            - service_network
    sentiment_serivce:
        image: sentiment_service
        container_name: sentiment_service
        ports:
            - 8002:8002
        networks:
            - service_network
    classification_service:
        image: classification_service
        container_name: classification_service
        ports:
            - 8003:8003
        networks:
            - service_network

networks:
    service_network:
        name: 'service_network'